NewsCenter/Areas/Admin/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Project.BLL.ManagerServices.Abstracts;
using Project.BLL.ManagerServices.Concretes;
using Project.ENTITIES.Enums;
using Project.ENTITIES.Models;

namespace NewsCenter.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class CommentController : Controller
    {
        readonly ICommentManager _commentManager;

        public CommentController(ICommentManager commentManager)
        {
            _commentManager = commentManager;
        }
        public IActionResult Index()
        {
            ViewBag.activeMenu = "Comment";
            List<Comment> data = _commentManager.GetAll();

            return View(data);
        }

        //yorum onaylama. Viewi yok oluşturulan butonun veritabanında iş yapmasını sağlar
        public async Task<IActionResult> ConfirmComment(int id)
        {
            Comment model = await _commentManager.FindAsync(id);
            model.CommentStatus = CommentStatus.Approved; //bulunan yoruun statüsünü onaylandı ya çek
            await _commentManager.UpdateAsync(model);
            return RedirectToAction("Index");
        }

        //onayı geri alma 
        public async Task<IActionResult> RevorkComment(int id)
        {
            Comment model = await _commentManager.FindAsync(id);

            if (model == null)
            {
                return NotFound();
            }
            model.CommentStatus = CommentStatus.PendingApproval; // Onay bekliyora geri al
            await _commentManager.UpdateAsync(model);
            return RedirectToAction("Index");
        }

        //yorumu reddet
        public async Task<IActionResult> RejectComment(int id)
        {
            Comment model = await _commentManager.FindAsync(id);

            if (model == null)
            {
                return NotFound();
            }
            model.CommentStatus = CommentStatus.Rejected; // Yorumu rejected(reddedildi) olarak ayarla
            await _commentManager.UpdateAsync(model);
            return RedirectToAction("Index");
        }
        //yorumu sil
        public async Task<IActionResult> DeleteComment(int id)
        {
            _commentManager.Delete(await _commentManager.FindAsync(id));
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DestroyComment(int id)
        {
            try
            {
                TempData["Message"] = _commentManager.Destroy(await _commentManager.FindAsync(id));

            }
            catch (Exception ex)
            {
                // Diğer tüm hatalar için genel bir yakalama bloğu
                TempData["Message"] = "Yorum silme işlemi sırasında bir hata oluştu: " + ex.Message;

            }
            return RedirectToAction("Index");
        }
    }
}

NewsCenter/Controllers/NewsDetailController.cs
using Microsoft.AspNetCore.Mvc;
using NewsCenter.Models;
using Project.BLL.ManagerServices.Abstracts;
using Project.BLL.ManagerServices.Concretes;
using Project.ENTITIES.Enums;
using Project.ENTITIES.Models;
using System.CodeDom;
using System.Diagnostics;
using System.Security.Claims;

namespace NewsCenter.Controllers
{
    public class NewsDetailController : Controller
    {
        private readonly ILogger<NewsDetailController> _logger;
        private readonly INewsManager _newsManager;
        private readonly ICommentManager _commentManager;
       
        public NewsDetailController(INewsManager newsManager, ICommentManager commentManager)
        {
            _newsManager = newsManager;
            _commentManager = commentManager;
        }
        public async Task<IActionResult> Index(int id)
        {
            //haber için
            News n = await _newsManager.FindAsync(id);
            ViewBag.NewsDetail = n;

            //yeni yorum modeli
            Comment cm = new Comment();
            cm.NewsID = id;

            //Habere ait tüm yorumlar
            List<Comment> commentList = _commentManager.Where(x=>x.NewsID == id && x.CommentStatus == CommentStatus.Approved).ToList() ;
            ViewBag.Comments = commentList;
            return View(cm);
        }


        [HttpPost]
        public async Task<IActionResult> CreateComment(Comment comment)
        {
            comment.AppUserID = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier)); // oturum açmış olan kullanıcının ıdsi
            comment.CommentStatus = CommentStatus.PendingApproval;
            await _commentManager.AddAsync(comment);
            return RedirectToAction("Index", new {ID = comment.NewsID});
        }

    }
}

NewsCenter/Areas/Admin/Views/Comment/Index.cshtml
@model List<Comment>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@{

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml"; //Bu sayfa bu adresteki layouta bağlı olarak çalışsın

    var user = await UserManager.GetUserAsync(User); // Oturum açmış kullanıcıyı alıyoruz.

}


<h4 class="fw-bold">@TempData["Message"]</h4>
<section class="panel">
    <div class="panel-body">
        <div class="adv-table">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Kullanıcı</th>
                        <th scope="col">Haber Başlığı</th>
                        <th scope="col">Yorum</th>
                        <th scope="col">Onay Durumu</th>
                        <th scope="col">Oluşturulma Tarihi</th>
                        <th scope="col">Güncellenme Tarihi</th>
                        <th scope="col">Silinme Tarihi</th>
                        @{
                            if (user != null && await UserManager.IsInRoleAsync(user, "Admin")) // kullanıcı rollerinde admin varsa işlemler yazısını göster.
                            {
                                <th class="hidden-phone">İşlemler</th>
                            }

                        }

                    </tr>
                </thead>
                <tbody>
                    @foreach (Comment item in Model)
                    {
                        <tr>
                            <th scope="row">@item.ID</th>
                            <td>@item.AppUser.Profile.FirstName @item.AppUser.Profile.LastName </td>
                            <th scope="row"><a target="_blank" href="@Url.Action("Index", "NewsDetail", new {area = "" , id = item.News.ID })">@item.News.Header</a></th>
                            <td>@item.CommentText  </td>
                            <td>@item.CommentStatus</td>
                            <td>@item.CreatedDate </td>
                            <td>@item.ModifiedDate </td>
                            <td>@item.DeletedDate</td>
                            @{
                                if (user != null && await UserManager.IsInRoleAsync(user, "Admin")) // kullanıcı rollerinde admin varsa işlemler yazısını göster.
                                {
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="fas fa-cog"></i>
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li><a asp-action="ConfirmComment" asp-route-id="@item.ID" type="button" class="dropdown-item"> <i class="fas fa-check"></i> Onayla</a></li>
                                                <li><a asp-action="RevorkComment" asp-route-id="@item.ID" type="button" class="dropdown-item"> <i class="fas fa-history"></i> Onayı Geri Al</a></li>
                                                <li><a asp-action="RejectComment" asp-route-id="@item.ID" type="button" class="dropdown-item"> <i class="fas fa-ban"></i> Reddet</a></li>
                                                <li><a asp-action="DeleteComment" asp-route-id="@item.ID" class="dropdown-item"> <i class="fas fa-eraser"></i>  Sil </a> </li>
                                                <li>
                                                    <a asp-action="DestroyComment" asp-route-id="@item.ID" class="dropdown-item">
                                                        <i class="fas fa-trash"></i>
                                                        Yok Et
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>

                                    </td>
                                }

                            }
                           

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>